### ISSUE TITLE
Place names list of person records

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#209]
In after the place name Doliche is strange. It shouldn't be there. 

![in](https://user-images.githubusercontent.com/18262359/47727136-c298f300-dc53-11e8-927e-9fe4dd4f0c9b.PNG)

**Comment by tuurma** [comment]
Now fixed - it was due to a change in editor, where we changed from leaving the place modifier empty to explicitly marking it as 'in' the place. This is all happening under the hood, but I didn't adjust the display accordingly.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/449468/47775661-91223500-dcf0-11e8-84e1-133ca78a1ef6.png">
