### ISSUE TITLE
a lost place name: Chalcis

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#218]
Chalcis (Syria) does not appear in the alphabetical list of place names...although in the form it appears in the drop box  for places...

**Comment by tuurma** [comment]
Should be fixed with the update tonight, here's a screenshot of my local version

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/449468/52855642-5074ed00-3122-11e9-9400-0458102256b2.png">

**Comment by JSBLGPN** [comment]
same problem as before: on Michael's computer too

**Comment by tuurma** [comment]
Oh, I think I know what it is: Chalcis does show up on the list shown from Place catalogue > C
but not in the alphabetical list of place names for volume, because no person is associated with this place. 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/449468/53093271-45053580-3517-11e9-8a9f-86f501b38582.png">
