### ISSUE TITLE
list of catalogue: Hauran: sub-places nowhere to be found

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#223]
There are two Hauran: one in Syria (I'd like to delete this one) and one in Arabia (which needs to be kept).

Under Hauran (Syria) the catalogue indicates two sub-places: I can't find them neither in nested catalogue or in alaphbetically catalogue

**Comment by tuurma** [comment]
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/449468/53241366-c688cf00-36a1-11e9-869f-c38ca45547e8.png">

This nested place is Nimra (Place id Pd26f6d83-1cce-4e9f-a745-c53e00d87c59)  but it has no people listed which is why it doesn't appear in V6 listing. I will think how to add this information to the place catalogue.

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/449468/53241651-9d1c7300-36a2-11e9-946b-3bf1dd840116.png">

**Comment by JSBLGPN** [comment]
Ok I will delete these two places, thanks

**Comment by tuurma** [comment]
It's not looking too pretty atm but I've added a small tooltip to the list of places, upon hovering over the number of sub-places the names of these nested places are displayed

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/449468/53643414-44b21c00-3c34-11e9-800d-1ae8a923f3a5.png">

**Comment by JSBLGPN** [comment]
Indeed if there are many nested places (like DAMASKOS) they all come indistinctly one after the other "in a queue", perhaps they could be displayed in a column.  But it is helpful, thanks.
