### ISSUE TITLE
generations

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#238]
Here is an example where generations should run from I to III.
Ergeas III being the last one.

![image](https://user-images.githubusercontent.com/18262359/57306475-cb72f180-70da-11e9-82fe-8a864ed9f455.png)

**Comment by tuurma** [comment]
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/index.html?sort=update&browse=name&filter=Ἐργέας

Should be:

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/449468/58411470-a4be3000-8074-11e9-83d0-ceb74a5dcd4f.png">

**Comment by tuurma** [comment]
Incorrectly assigned to places (all 8 end up under Antioch)

![image](https://user-images.githubusercontent.com/449468/58415490-f10e6d80-807e-11e9-9814-4f2fec448c55.png)

<img width="770" alt="image" src="https://user-images.githubusercontent.com/449468/58415517-ff5c8980-807e-11e9-8ee2-ac13c8d19bc8.png">

**Comment by tuurma** [comment]
Counting now fixed on my local instance, just missing Roman numerals

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/449468/58418341-da204900-8087-11e9-9153-574d0312a408.png">

**Comment by tuurma** [comment]
Numbering fixed on my local, also figured out why there are 8 entries instead of 3. All are citizens of Antioch but attested at Orchomenos and Akraiphia.

Changes will be visible on the server after next update. 

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/449468/58418662-b6113780-8088-11e9-8d83-aa3fed28b0b6.png">
