### ISSUE TITLE
names with superfluous space

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#261]
@michaelzellmann I've found some entries where canonical name form contains extra space which disturbs pdf generation - such names are considered different and result in separate listing.

I will add validation warning to the name form but currently have limited access to the server due to some firewall problems on the Oxford side. List below shows existing entries which require intervention

http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/nymRefWithWhitespace.xql

**Comment by michaelzellmann** [comment]
Many thanks, I’ve re-keyed all of these and they now seem to disappear from the list when refreshed, so hope it is solved. With the exception of Ια: the autocomplete requires at least 3 characters, so an extra space is necessary unless you can override that somehow in this case; the name is complete just as Ια with two characters

On Oct 29, 2019, at 12:47 PM, Magdalena Turska <notifications@github.com<mailto:notifications@github.com>> wrote:


@michaelzellmann<https://github.com/michaelzellmann> I've found some entries where canonical name form contains extra space which disturbs pdf generation - such names are considered different and result in separate listing.

I will add validation warning to the name form but currently have limited access to the server due to some firewall problems on the Oxford side. List below shows existing entries which require intervention

http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/nymRefWithWhitespace.xql

**Comment by tuurma** [comment]
fixed Ia, closing
