### ISSUE TITLE
Redesign bibl subform (`bibl.xhtml`)

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/LGPN#85]
Needs to be fixed as well, because the included css `editor.css` was replaced by the new layout `style.css` 

Related #80, #73

**Comment by tuurma** [comment]
The structure we had for bibliographic entry was

```xml

    <biblFull xml:id="LGPN2">
        <titleStmt>
            <title>Lexicon of Greek Personl Names v2</title>
            <title type="sub">Attica</title>
            <title type="abbr">LGPN II</title>
            <respStmt>
                <resp>editor</resp>
                <name>Osborne, M. J.</name>
            </respStmt>
            <respStmt>
                <resp>editor</resp>
                <name>Byrne, S. G.</name>
            </respStmt>
        </titleStmt>
        <publicationStmt>
            <publisher>Clarendon Press Oxford</publisher>
            <pubPlace>Oxford</pubPlace>
            <date>1994</date>
        </publicationStmt>
    </biblFull>
```

Since in fact we do not need full bibliographic entries, rather only list of abbreviations, it makes no sense to deal with all the complexity of bibliography and we have agreed to simplify it, reflecting for the large part the original Ingres database of the Lexicon.

- id (text input, xml:id)
- abbr (text input) *holding the abbreviation label for an entry; this may contain + signs signalling italicized parts*
- suppressed (dropdown/checkbox) *if selected, an entry should not be included in abbreviation lists generated for the book*
- desc (text input) *full reference; may contain + or {} signalling italicized or superscript parts
- patterns (multiple select dropdown/checkbox) *patterns applicable for this entry*

**Comment by tuurma** [comment]
New structure

```xml

<bibl xml:id="" ana="" type="">
   <abbr><!-- abbreviation --></abbr>
   <bibl><!-- full reference --></bibl>
</bibl>
```

**Comment by tuurma** [comment]
```xml

<bibl xml:id="EnclItal" ana="BP1" type="LGPN">
   <abbr>+Encl. +Ital.</abbr>
   <bibl>+Enciclopedia +Italiana (Rome, 1958-64)</bibl>
</bibl>
```

**Comment by tuurma** [comment]
Two-patterned example 

```xml
<bibl xml:id="KrollAthAllotPlates" ana="BP2 BP1" type="LGPN">
   <abbr>Kroll, +Ath. +Allot. +Plates</abbr>
   <bibl>J. Kroll, +Athenian +Bronze +Allotment +Plates (Cambridge, Mass., 1972)</bibl>
</bibl>
```

**Comment by plutonik-a** [comment]
### Desktop
<img width="919" alt="bildschirmfoto 2017-06-15 um 15 56 35" src="https://user-images.githubusercontent.com/1157669/27185004-3c2b4fac-51e4-11e7-8732-d7bb0a53a63d.png">

### Tablet/medium device width
<img width="893" alt="bildschirmfoto 2017-06-15 um 15 56 07" src="https://user-images.githubusercontent.com/1157669/27185028-4b1cfa88-51e4-11e7-8355-b663a05709fe.png">

### Small device width
<img width="309" alt="bildschirmfoto 2017-06-15 um 15 51 14" src="https://user-images.githubusercontent.com/1157669/27185043-53262c4a-51e4-11e7-83a5-d15751fd4bea.png">

**Comment by tuurma** [comment]
looks like we are done here, closing
