### ISSUE TITLE
[general] and [primary source] [date]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#97]
If possible display [date] [not before] and [date] [not after] directly one above the other

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27184143-1a6cff42-51d9-11e7-944d-d137f4759a8f.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27184210-5c091652-51d9-11e7-946f-82428ba6e167.png)

**Comment by plutonik-a** [comment]
@tuurma 
This is how the input order on smaller than average desktop screens looks like:

<img width="307" alt="bildschirmfoto 2017-06-16 um 13 10 12" src="https://user-images.githubusercontent.com/1157669/27224633-86ea3f46-5296-11e7-8b38-9a9cb89cb574.png">

The problem here is: The ordering of the inputs in columns is done via floating. With this technique you are not flexible enough to change the order of the elements depending on the device width. We use the floating technique because the project depends on Bootstrap 3 which relies on floating elements. 

Working around this by using grid layout or flexbox layout, where you are free to order elements in any position depending on device width, will take too much effort for this purpose.

We could either leave the horizontal ordering of start and end date, like generally most date UIs prefer, or we could implement a date picker here.

**Comment by tuurma** [comment]
Thanks @plutonik-a, I don't think we need to worry about small screens,
intended use here is for people on desktops/laptops, so I don't see much
benefit in spending time on making it extremely responsive. Date picker
wouldn't help us here as our dates span roughly 18 centuries :-)
